[package]
name = "pendu_rust"
version = "0.1.0-beta"
edition = "2021"
description = "Le fameux 'jeu du pendu' que tout le monde connait."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"